FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    python3-pip \
    tzdata

COPY requirements.txt .
RUN pip3 install -r requirements.txt

ARG PRIVAT_API_ID
ARG PRIVAT_API_TOKEN
ARG ACCOUNTS

ARG GOOGLE_APPLICATION_CREDENTIALS
ARG GOOGLE_SPREADSHEET_KEY
ARG GOOGLE_WORKSHEET_TITLE

ARG TELEGRAM_BOT_TOKEN

ARG DB_DIR

ENV PRIVAT_API_ID=$PRIVAT_API_ID
ENV PRIVAT_API_TOKEN=$PRIVAT_API_TOKEN
ENV ACCOUNTS=$ACCOUNTS

ENV GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
ENV GOOGLE_SPREADSHEET_KEY=$GOOGLE_SPREADSHEET_KEY
ENV GOOGLE_WORKSHEET_TITLE=$GOOGLE_WORKSHEET_TITLE

ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN

ENV DB_DIR=$DB_DIR
ENV TZ=Europe/Kiev

COPY $GOOGLE_APPLICATION_CREDENTIALS .
COPY pb2gsheet.py .

CMD python3 pb2gsheet.py
