FROM ubuntu:20.04

ARG INSTALLER
ARG INSTALLER_PATH=/installer.exe
ARG AUTOCLIENT_DIR=/autoclient
ARG AUTOCLIENT_EXE=AutoClient.exe

ENV AUTOCLIENT_DIR=$AUTOCLIENT_DIR
ENV AUTOCLIENT_EXE=$AUTOCLIENT_EXE

ENV WINEARCH win32

COPY $INSTALLER $INSTALLER_PATH

RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y --no-install-recommends wine wine32 xvfb

RUN xvfb-run wine $INSTALLER_PATH /VERYSILENT /DIR=$AUTOCLIENT_DIR
RUN rm -f $INSTALLER_PATH

WORKDIR $AUTOCLIENT_DIR
CMD wine $AUTOCLIENT_EXE
